### ISSUE TITLE
DATABASE_URL ?

### ISSUE THREAD

**Issue by Klaudioz** [wasp-lang/SaaS-Template-GPT#1]
According the [env.server.example](https://github.com/wasp-lang/SaaS-Template-GPT/blob/master/env.server.example)

```
# NOTE: if you setup your DB using `wasp start db` then you DO NOT need to add a DATABASE_URL env.
# DATABASE_URL=
```

What about if I'm using fly.io ?

`Run wasp deploy fly create-db mia`

Do I need to setup the DB in this case?

**Comment by Lezzz** [comment]
`5. Run wasp deploy fly create-db mia`

I think you don't have to manually set it if you deploy on fly.io as it gets created and set-up here on step 5. But please correct me if I'm wrong.

**Comment by Martinsos** [comment]
@Lezzz thanks Lezzz, that is correct! The comment was addressing the development database. When deploying somewhere, it depends on where you deploy. Specifically, when using our `wasp deploy fly`, that is done for you.
