### ISSUE TITLE
How would you implement the payment by credits

### ISSUE THREAD

**Issue by RaigaK** [wasp-lang/SaaS-Template-GPT#4]
Disclaimer : im learning react + tailwindcss with Wasp

I have most of my frontend ready, and i want to implement the credits

Do i need to implement another type of stripePayment and another clickHandler ? 
For example this ? 

```
export const stripeCreditsPayment: StripePayment<void, StripePaymentResult> = async (_args, context) => {
  if (!context.user) {
    throw new HttpError(401);
  }
  let customer: Stripe.Customer;
  const stripeCustomers = await stripe.customers.list({
    email: context.user.email!,
  });
  if (!stripeCustomers.data.length) {
    console.log('creating customer');
    customer = await stripe.customers.create({
      email: context.user.email!,
    });
  } else {
    console.log('using existing customer');
    customer = stripeCustomers.data[0];
  }

  const session: Stripe.Checkout.Session = await stripe.checkout.sessions.create({
    line_items: [
      {
        price: process.env.CREDITS_PRICE_ID!,
        quantity: 1,
      },
    ],
    mode: 'payment',
    success_url: `${DOMAIN}/checkout?success=true`,
    cancel_url: `${DOMAIN}/checkout?canceled=true`,
    automatic_tax: { enabled: false },
    customer_update: {
      address: 'auto',
    },
    customer: customer.id,
  });

  await context.entities.User.update({
    where: {
      id: context.user.id,
    },
    data: {
      checkoutSessionId: session?.id ?? null,
      stripeId: customer.id ?? null,
    },
  });

  return new Promise((resolve, reject) => {
    if (!session) {
      reject(new HttpError(402, 'Could not create a Stripe session'));
    } else {
      resolve({
        sessionUrl: session.url,
        sessionId: session.id,
      });
    }
  });
};`
```

Because i actualy did that and now my stripeCreditsPaymet(); is asking for Args. 

`  const clickCreditHandler = async () => {
    setIsLoading(true);
    try {
      const response = await stripeCreditsPayment();
      if (response?.sessionUrl) {
        window.open(response.sessionUrl, '_self');
      }
    } catch (e) {
      setCreditIsOpen(!isCreditOpen);
      console.error(e);
    } finally {
      setIsLoading(false);
    }
  };`

Im not using Map to iterate on the prices. so im doing it manually. 
I just need some guidance. on what im doing wrong 

these are my actions 

```
action stripePayment {
  fn: import { stripePayment } from "@server/actions.js",
  entities: [User]
}

action stripeCreditsPayment {
  fn: import { stripeCreditsPayment } from "@server/actions.js",
  entities: [User]
```

**Comment by RaigaK** [comment]
Nevermind had to uncoment the new action that wasp made for me and import it with @wasp/actions/xxxxx
ty

**Comment by Martinsos** [comment]
Great to hear it worked @Arukaito ! Anything you think we can do on our side regarding this, improve something regarding DX / docs? How is your experience so far?
